{% set name = "clyngor" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03768c37a3bfead862ad2bc2e39abd8da13f080deea37f7b59050c821f6ab145

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - arpeggio >=1.6.1
    - pypeg2 >=2.15.2
    - pytest >=3.2.1
  run:
    - python
    - arpeggio >=1.6.1
    - pypeg2 >=2.15.2

test:
  imports:
    - clyngor

about:
  home: https://github.com/aluriak/clyngor
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE
  summary: Handy python wrapper around Potassco's Clingo ASP solver.

extra:
  recipe-maintainers:
    - raivivek
